AWSTemplateFormatVersion: 2010-09-09
Parameters:
  CustomerName:
    Type: String
    Description: Customer-1
    Default: Customer-1
    
Resources:
  # S3 Bucket Creation
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

  # Bucket Policy to allow public access
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'

  # Custom Resource for index.html upload
  S3BucketIndexHtml:
    Type: 'Custom::S3Object'
    Properties:
      ServiceToken: !GetAtt S3BucketFunction.Arn
      BucketName: !Ref S3Bucket
      Key: 'index.html'
      Content: !Sub |
        
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link rel="stylesheet" href="index.css">
            <script src="index.js"></script>
            <title>Cloud Watch Metrics</title>
            <style>
            body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #ffffff;
            margin: 0;
            padding: 0;
            color: #2c3e50;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            min-height: 100vh;
            background-image: url('https://cdwcustomapplication.s3.amazonaws.com/image_(4)-j1f3dsnvn-transformed.jpeg');
            background-size: contain; /* Fits the image proportionally */
            background-position: center;
            background-repeat: no-repeat; /* Prevents tiling of the image */
            background-attachment: fixed; /* Keeps the image fixed while scrolling */ }
            .container {
            margin-top: 20px;
            background-color: rgba(255, 255, 255, 0.85);
            border-radius: 15px;
            padding: 30px;
            box-shadow: 0 5px 20px rgba(0, 0, 0, 0.1);  }
            .row {
            margin-bottom: 20px;  }
            p {
            font-size: 28px;
            font-weight: bold;
            color: #1a3e59; /* Deep navy blue for the text */ }
            label {
            font-weight: bold;
            color: #ff4d4d; }
            input[type="number"],
            select {
            border: 2px solid #ff4d4d;
            border-radius: 5px;
            padding: 10px;
            font-size: 16px; }
            button {
            background-color: #ff4d4d;
            color: white;
            font-weight: bold;
            padding: 10px 20px;
            border-radius: 30px;
            border: none;
            transition: background-color 0.3s ease, transform 0.3s ease; }
            button:hover {
            background-color: #e03b3b;
            transform: scale(1.05);  }
            a {
            display: inline-block;
            margin-top: 20px;
            text-decoration: none;
            color: white;
            background-color: #2c3e50;
            padding: 10px 25px;
            border-radius: 25px;
            transition: background-color 0.3s ease;  }
            a:hover {
            background-color: #34495e; }
            </style>
        </head>
        <body>
            <img src="cdw-2023-Red.png" alt="CDW Logo">
            <div class="container">
            <div class="row">
                  <div class="col-sm m-1">
                  <section style="text-align: center">
                        <p>Customer-1 Orange Team</p>
                        <br><br>
                  </section>
                  </div>
            </div>
            <div class="row justify-content-center">
                  <div class="col">
                  <form>
                        <div class="form-group">
                        <label for="timeframeLength">Duration:</label>
                        <input type="number" min="1" max="100" onkeypress="return event.charCode >= 48" class="form-control" id="timeframeLength" aria-describedby="timeframeLength" placeholder="2" oninput="enableButton()">
                        </div>
                  </form>
                  </div>
                  <div class="col">
                  <label for="timeframeUnit">Unit of time:</label>
                  <select name="timeframeUnit" id="timeframeUnit" class="custom-select">
                        <option selected>Weeks</option>
                        <option value="minutes">Minutes</option>
                        <option value="hours">Hours</option>
                        <option value="days">Days</option>
                  </select>
                  </div>
                  <div class="col" style="display: flex; justify-content: center; align-items: center;">
                  <button type="button" class="btn btn-secondary btn-block" style="margin-top: 13px;" id="customTimeButton" onClick="submitCustomTimeframe()" disabled>Go</button>
                  </div>
            </div>
            </div>
            <div class="container">
            <div class="row justify-content-center" id="sectionResults">
                  <section style="text-align: center" class="row loading">
                  <!-- Loading results will appear here -->
                  </section>
            </div>
            <div class="row">
                  <section class="col" id="results">
                  <!-- Results will be displayed here -->
                  </section>
            </div>
            </div>
            <a href="https://myuserpool-domain.auth.us-east-1.amazoncognito.com/logout?client_id=3qtbgn503ttnmd75qc6iat3vnt&logout_uri=https%3A%2F%2Fcdwcustomer1.s3.amazonaws.com%2Flogged_out.html">Click to log out</a>
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        </body>
        </html>
        
      ContentType: 'text/html'

  S3BucketloggedoutHtml:
    Type: 'Custom::S3Object'
    Properties:
      ServiceToken: !GetAtt S3BucketFunction.Arn
      BucketName: !Ref S3Bucket
      Key: 'loggedout.html'
      Content: !Sub |
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Logging Out</title>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <style>
                body {
                    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                    margin: 0;
                    padding: 0;
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    flex-direction: column;
                    color: #1a3e59;
                    min-height: 100vh;
                    background-image: url('https://cdwcustomapplication.s3.amazonaws.com/image_(4)-j1f3dsnvn-transformed.jpeg');
                    background-size: contain;
                    background-position: center;
                    background-repeat: no-repeat;
                    background-attachment: fixed;
                }

                .container {
                    background-color: rgba(255, 255, 255, 0.85);
                    border-radius: 15px;
                    padding: 30px;
                    box-shadow: 0 5px 20px rgba(0, 0, 0, 0.1);
                    text-align: center;
                    max-width: 500px;
                }

                h3 {
                    color: #ff4d4d;
                    font-weight: bold;
                }

                p {
                    margin-top: 20px;
                    font-size: 18px;
                    color: #1a3e59;
                }

                a {
                    display: inline-block;
                    margin: 15px 0;
                    text-decoration: none;
                    color: white;
                    background-color: #2c3e50;
                    padding: 10px 25px;
                    border-radius: 25px;
                    font-size: 16px;
                    transition: background-color 0.3s ease;
                }

                a:hover {
                    background-color: #34495e;
                }
            </style>
        </head>

        <body>
            <img src="cdw-2023-Red.png" alt="CDW Logo">
            <div class="container">
                <h3>Logging out, bye!</h3>
                <p>Log in again:</p>
                <a href="https://myuserpool-domain.auth.us-east-1.amazoncognito.com/login?client_id=3qtbgn503ttnmd75qc6iat3vnt&response_type=code&scope=email+openid&redirect_uri=https%3A%2F%2Fcdwcustomer1.s3.amazonaws.com%2Findex.html">Login Back</a>
                <p>Go To Home Page:</p>
                <a href="http://cdwcustomapplication.s3-website-us-east-1.amazonaws.com/">HOME</a>
            </div>
        </body>

        </html>

      ContentType: 'text/html'

  S3BucketIndexCss:
    Type: 'Custom::S3Object'
    Properties:
      ServiceToken: !GetAtt S3BucketFunction.Arn
      BucketName: !Ref S3Bucket
      Key: 'index.css'
      Content: !Sub |
        /* table, th, td {
        border: 1px solid black;} */
        th,
        td {
          padding: 5px;
          text-align: center;
        }

        p {
          font-size: 50px;
        }

        #timeframeLength:focus::placeholder {
          color: transparent;
        }
      ContentType: 'text/css'

  S3BucketIndexJs:
    Type: 'Custom::S3Object'
    Properties:
      ServiceToken: !GetAtt S3BucketFunction.Arn
      BucketName: !Ref S3Bucket
      Key: 'index.js'
      Content: !Sub |
        async function initialFetchCloudWatchData() {
          let baseURL = "https://e7jk6o4svh.execute-api.us-east-1.amazonaws.com/testing/yamlcloudwatchtest";
          try {
            let response = await fetch(baseURL);
            if (!response.ok) {
              return {
                "errorMessage": response,
                "result": false
              };
            } else {
              let cloudWatchData = await response.json();
              return {
                "data": cloudWatchData,
                "result": true
              };
            }
          } catch (err) {
            return {
              "errorMessage": err,
              "result": false
            };
          }
        }
        # ... rest of your JavaScript code ...
      ContentType: 'application/javascript'


  # Lambda Function to handle the custom resource
  S3BucketFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: 'index.handler'
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          def handler(event, context):
              s3 = boto3.client('s3')
              bucket = event['ResourceProperties']['BucketName']
              key = event['ResourceProperties']['Key']
              content = event['ResourceProperties']['Content']
              content_type = event['ResourceProperties']['ContentType']
              s3.put_object(Bucket=bucket, Key=key, Body=content, ContentType=content_type)
              cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
      Runtime: 'python3.9'
      Timeout: 30

  # IAM Role for Lambda function
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'S3AccessPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:PutObject'
                  - 's3:PutObjectAcl'
                Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'

Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content
